Repository UnBArqDsw2021-2/2021.2_G2_Ki-Limpinho, pull requests merged in 2022-02, with the labels that each got.

#48 [Feature] Adição documento protótipo de média fidelidade
  docs/prototipoBaixa.md
  docs/prototipoMedia.md
  mkdocs.yml
Labels: documentation

#19 5- Documento de Metodologia
  docs/metodologia_do_projeto.md
  mkdocs.yml
Labels: documentation, Sprint 1

#77 73-entidade relacionamento
  docs/assets/img/mer/mer.jpeg
  docs/mer.md
  mkdocs.yml
Labels: review

#81 80-RastreabilidadeMOSCOW
  docs/modelagem/priorizacao/moscow.md
Labels: review

#78 #69 DiagramaDeEstado
  docs/assets/img/diagrama/componentes.png
  docs/assets/img/diagrama/login.png
  docs/diagramaDeEstado.md
  mkdocs.yml
Labels: review

#87 adicao do diagrama de implementacao #68
  docs/modelagem/diagramas/diagramaDeImplementacao.md
  mkdocs.yml
Labels: documentation, sprint3, diagrams

#89 70 diagrama atividades
  docs/assets/img/diagrama_atividades/cadastro_usuario.jpeg
  docs/assets/img/diagrama_atividades/cancelamento_ou_remarcar.jpeg
  docs/assets/img/diagrama_atividades/fluxo_de_caixa.jpeg
  docs/assets/img/diagrama_atividades/pagamento_servico.jpeg
  docs/diagrama_de_atividades.md
  mkdocs.yml
Labels: documentation, review, diagrams

#85 #72 diagrama de sequencia
  docs/assets/img/sequencia/ag_serv.png
  docs/assets/img/sequencia/av_cli.png
  docs/assets/img/sequencia/ger_cadIliistOp.png
  docs/assets/img/sequencia/seq_createUser.png
  docs/diagramaDeSequencia.md
  mkdocs.yml
Labels: documentation, sprint3, diagrams

#100 67 diagrama de componentes
  .vscode/settings.json
  docs/assets/img/componentes/diagrama_componentes.png
  docs/diagramaDeComponentes.md
  mkdocs.yml
Labels: documentation, Modelagem estática

#101 92 tasks
  docs/modelagem/backlog.md
Labels: review, Sprint 4, Modelagem ágil

#103 #93 Prototipo de alta fidelidade
  docs/assets/stylesheets/extra.css
  docs/prototipagem/prototipoAlta.md
  docs/prototipagem/prototipoBaixa.md
  docs/prototipagem/prototipoMedia.md
  mkdocs.yml
Labels: documentation, Sprint 4
